<?php
class M_prepayment extends CI_Model{
	function __construct(){
		parent::__construct();
	}

	public function getLaporan($org_id, $sitesuppRaw, $tanggal)
	{

		if ($sitesuppRaw == '' || $sitesuppRaw == NULL) {
			$sitesupp = '';
		}else{
			$sitesupp = "AND PVS.VENDOR_SITE_CODE LIKE '".$sitesuppRaw."'";
		};
		$tanggal = date('d/M/Y');
		$oracle = $this->load->database("oracle",true);
		$query = $oracle->query("
			SELECT PREPAY.*
			FROM
			(
			SELECT
				HAOU.NAME BRANCH,
				AI.VENDOR_ID,	
				NVL(PV.VENDOR_NAME, HP.PARTY_NAME) VENDOR_NAME , 
				AI.INVOICE_NUM NO_INV_PREPAYMENT,
				AI.ATTRIBUTE15 NO_VOUCHER,  
				AI.PAYMENT_CURRENCY_CODE, 
				NVL(AI.EXCHANGE_RATE,1) RATE_PREPAYMENT,
				(select sum(aila.amount)
				from AP_INVOICE_LINES_ALL AILA
				WHERE AILA.INVOICE_ID = AI.INVOICE_ID
				AND aila.LINE_TYPE_LOOKUP_CODE = 'ITEM'
				AND (AILA.DISCARDED_FLAG = 'N' OR AILA.DISCARDED_FLAG IS NULL) 
				AND (CANCELLED_FLAG = 'N' OR CANCELLED_FLAG IS NULL)) AMOUNT,
				 (select sum(aila.amount)
				from AP_INVOICE_LINES_ALL AILA
				WHERE AILA.INVOICE_ID = AI.INVOICE_ID
				AND aila.LINE_TYPE_LOOKUP_CODE = 'ITEM'
				AND (AILA.DISCARDED_FLAG = 'N' OR AILA.DISCARDED_FLAG IS NULL) 
				AND (CANCELLED_FLAG = 'N' OR CANCELLED_FLAG IS NULL))*NVL(AI.EXCHANGE_RATE,1) AMOUNT_IDR,
				NVL(AI.TOTAL_TAX_AMOUNT,0) PPN,
				NVL((SELECT 
							SUM (AIL2.AMOUNT*-1)   
						 FROM
							AP_INVOICE_LINES_ALL AIL2,
							AP_INVOICES_ALL AI2,
							AP_INVOICES_ALL AIA2
						 WHERE
							AIA2.INVOICE_ID(+) = AIL2.INVOICE_ID
							AND AIL2.PREPAY_INVOICE_ID(+) = AI2.INVOICE_ID
							AND ail2.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
							AND AI2.INVOICE_NUM =AI.INVOICE_NUM
							AND AI2.VENDOR_ID = AI.VENDOR_ID
							AND AIA2.GL_DATE <= trunc(TO_DATE('$tanggal'))),0) AMOUNT_PAID,
				((select sum(aila.amount)
				from AP_INVOICE_LINES_ALL AILA
				WHERE AILA.INVOICE_ID = AI.INVOICE_ID
				AND aila.LINE_TYPE_LOOKUP_CODE = 'ITEM'
				AND (AILA.DISCARDED_FLAG = 'N' OR AILA.DISCARDED_FLAG IS NULL) 
				AND (CANCELLED_FLAG = 'N' OR CANCELLED_FLAG IS NULL))-
					NVL((SELECT 
						SUM (AIL2.AMOUNT*-1)   
					 FROM
						AP_INVOICE_LINES_ALL AIL2,
						AP_INVOICES_ALL AI2,
						AP_INVOICES_ALL AIA2
					 WHERE
						AIA2.INVOICE_ID(+) = AIL2.INVOICE_ID
						AND AIL2.PREPAY_INVOICE_ID(+) = AI2.INVOICE_ID
						AND AI2.INVOICE_NUM =AI.INVOICE_NUM
						AND AI2.VENDOR_ID = AI.VENDOR_ID
						AND ail2.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
						AND AIA2.GL_DATE <= trunc(TO_DATE('$tanggal'))),0)
				) SALDO_PREPAY,
			   ((select sum(aila.amount)
				from AP_INVOICE_LINES_ALL AILA
				WHERE AILA.INVOICE_ID = AI.INVOICE_ID
				AND aila.LINE_TYPE_LOOKUP_CODE = 'ITEM'
				AND (AILA.DISCARDED_FLAG = 'N' OR AILA.DISCARDED_FLAG IS NULL) 
				AND (CANCELLED_FLAG = 'N' OR CANCELLED_FLAG IS NULL))-
						NVL((SELECT 
							SUM (AIL2.AMOUNT*-1)   
						 FROM
							AP_INVOICE_LINES_ALL AIL2,
							AP_INVOICES_ALL AI2,
							AP_INVOICES_ALL AIA2
						 WHERE
							AIA2.INVOICE_ID(+) = AIL2.INVOICE_ID
							AND AIL2.PREPAY_INVOICE_ID(+) = AI2.INVOICE_ID
							AND AI2.INVOICE_NUM =AI.INVOICE_NUM
							AND ail2.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
							AND AI2.VENDOR_ID = AI.VENDOR_ID
							AND AIA2.GL_DATE <= trunc(TO_DATE('$tanggal'))),0)
				  ) * NVL(AI.EXCHANGE_RATE,1) SALDO_PREPAY_IDR,  
				IBY1.PAYMENT_METHOD_NAME,	   
			   ALC.DISPLAYED_FIELD APPROVAL_STATUS_LOOKUP_CODE ,  
				PVS.VENDOR_SITE_CODE VENDOR_SITE_CODE,
				PVS.ADDRESS_LINE1 NAMA,   
				AC.CHECK_DATE PAYMENT_DATE,				 
				AI.INVOICE_DATE INV_PREPAYMENT_DATE,
				(SELECT 
						NVL(PH.CLM_DOCUMENT_NUMBER, PH.SEGMENT1) 
					FROM 
						PO_HEADERS_ALL PH
					WHERE
						AI.QUICK_PO_HEADER_ID = PH.PO_HEADER_ID )NO_PO,	  
				AI.DESCRIPTION,
				AC.CHECK_NUMBER,
				PHA.SEGMENT1 PO_NUMBER
			FROM
				AP_INVOICES_ALL AI,
				PO_VENDOR_SITES_ALL PVS,
				PO_VENDORS   PV,	 
				HZ_PARTIES HP,
				IBY_PAYMENT_METHODS_VL IBY1 ,
				AP_LOOKUP_CODES ALC, 
				AP_CHECKS_ALL AC,
				AP_INVOICE_PAYMENTS_ALL  AIP ,
				HR_ALL_ORGANIZATION_UNITS   HAOU,
				PO_HEADERS_ALL PHA
			WHERE
				AI.APPROVAL_READY_FLAG <> 'S'	
				AND AI.INVOICE_TYPE_LOOKUP_CODE = 'PREPAYMENT'	
				AND AI.INVOICE_DATE <= trunc(TO_DATE('$tanggal'))
				AND AC.CHECK_DATE <= trunc(TO_DATE('$tanggal'))
				AND AI.VENDOR_SITE_ID = PVS.VENDOR_SITE_ID   
				AND AI.PARTY_ID  = HP.PARTY_ID
				AND PV.VENDOR_ID = AI.VENDOR_ID  
				AND AI.PAYMENT_METHOD_CODE = IBY1.PAYMENT_METHOD_CODE (+) 
				AND NVL(PV.VENDOR_NAME, HP.PARTY_NAME) = 'KHS Employee'
				$sitesupp
				AND ALC.LOOKUP_TYPE = 'PREPAY STATUS'
				AND ALC.LOOKUP_CODE = (AP_INVOICES_PKG.GET_APPROVAL_STATUS( AI.INVOICE_ID,
				  AI.INVOICE_AMOUNT, AI.PAYMENT_STATUS_FLAG,
				  AI.INVOICE_TYPE_LOOKUP_CODE))
				AND AI.ORG_ID =HAOU.ORGANIZATION_ID
				AND AI.ORG_ID = '$org_id'
				AND AIP.INVOICE_ID(+) = AI.INVOICE_ID	
				AND AIP.CHECK_ID = AC.CHECK_ID 
				AND AC.STATUS_LOOKUP_CODE != 'VOIDED'
				AND AI.PO_HEADER_ID = PHA.PO_HEADER_ID (+)
			ORDER BY
				 NVL(PV.VENDOR_NAME, HP.PARTY_NAME)
				 ,PVS.VENDOR_SITE_CODE
			) PREPAY
			WHERE SALDO_PREPAY_IDR > 0
		");
		return $query->result_array();
	}
	
}